Repository mfem/mfem, pull requests merged in 2019-07, with the labels that each got.

#980 Fix const correctness in eliminate* functions [bugfix-const-correctness]
  fem/bilinearform.cpp
  fem/bilinearform.hpp
Labels: bug, in-next, minor

#981 Fix an issue with the out-of-source build [out-of-source-build-fix]
  CMakeLists.txt
  config/config.hpp
  makefile
Labels: bug, building, in-next

#1001 In .appveyor.yml, update the source location for hypre [hypre-appveyor-update]
  .appveyor.yml
Labels: in-next, minor, testing
