Repository mfem/mfem, pull requests merged in 2019-04, with the labels that each got.

#697 Coarse mesh reordering for NC AMR [mesh-reordering-dev]
  CHANGELOG
  data/fichera.mesh
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/mesh_readers.cpp
  mesh/ncmesh.cpp
  mesh/ncmesh.hpp
  mesh/pncmesh.cpp
Labels: amr, enhancement, in-next, mesh

#811 Fix the boundary transformations on periodic meshes [periodic-mesh-bdr-transform-fix]
  mesh/mesh.cpp
Labels: enhancement, in-next, mesh

#817 Allow refinement of 1D (segment) meshes [refine-1d-mesh]
  mesh/mesh.cpp
Labels: in-next, mesh, minor

#827 [okina] Feedback updates [dmed256:okina]
  fem/bilininteg_ext.hpp
  fem/pbilinearform.cpp
  general/device.cpp
  general/device.hpp
  general/mm.cpp
  general/occa.hpp
  linalg/dtensor.hpp
  linalg/operator.cpp
  linalg/vector.cpp
  linalg/vector.hpp
Labels: GPU, minor

#829 OCCA all modes [okina-allin]
  examples/ex1.cpp
  fem/bilininteg_ext.cpp
  fem/defines.okl
  fem/diffusion.okl
  fem/mass.okl
  general/device.cpp
  general/mm.cpp
  general/occa.cpp
  general/occa.hpp
Labels: GPU, enhancement

#828 [okina] CUDA guards for non-nvcc builds [feature/okina-cuda-guards]
  config/defaults.mk
  general/cuda.hpp
  general/occa.hpp
  general/okina.hpp
Labels: GPU, building, enhancement

#833 [okina] Enable atomics to be usable on host when MFEM_USE_CUDA is defined [bugfix/artv3/okina-atomic]
  general/cuda.hpp
  general/occa.cpp
  linalg/sparsemat.cpp
Labels: enhancement, hpc

#834 Okina memory manager: replace new and delete with malloc and free in mm
  CHANGELOG
  fem/bilinearform.cpp
  fem/bilinearform_ext.cpp
  fem/bilininteg_ext.cpp
  fem/bilininteg_ext.hpp
  fem/coefficient.hpp
  fem/fespace.cpp
  fem/pfespace.cpp
  general/CMakeLists.txt
  general/array.cpp
  general/array.hpp
  general/cuda.hpp
  general/device.cpp
  general/device.hpp
  general/mem_manager.cpp
  general/mem_manager.hpp
  general/occa.cpp
  general/occa.hpp
  general/okina.hpp
  general/table.cpp
  linalg/CMakeLists.txt
  linalg/blockmatrix.cpp
  linalg/densemat.cpp
  linalg/densemat.hpp
  linalg/dtensor.hpp
  linalg/dvector3.hpp
  linalg/hypre.cpp
  linalg/linalg.hpp
  linalg/operator.cpp
  linalg/sparsemat.cpp
  linalg/vector.cpp
  linalg/vector.hpp
  mesh/ncmesh.cpp
  mesh/pmesh.cpp
  mfem.hpp
Labels: GPU, enhancement, general

#838 [okina] Add some typing in the mm to avoid void* [yohann/okina-gen-ptr]
  general/mem_manager.hpp
  linalg/dtensor.hpp
  linalg/sparsemat.cpp
Labels: enhancement, minor

#836 Use MFEM_INSTALL_DIR to find occa kernel locations [okina-occa-paths]
  config/config.hpp.in
  config/config.mk.in
  fem/bilininteg_ext.cpp
  general/device.cpp
  general/occa.hpp
  makefile
Labels: GPU, building

#780 Add deprecation warning for OpenMP [openmp-warning-dev]
  CHANGELOG
  CMakeLists.txt
  INSTALL
  config/cmake/MFEMConfig.cmake.in
  config/cmake/config.hpp.in
  config/cmake/modules/MfemCmakeUtilities.cmake
  config/config.hpp.in
  config/config.mk.in
  config/defaults.cmake
  config/defaults.mk
  fem/bilinearform.cpp
  fem/intrules.cpp
  general/version.cpp
  linalg/sparsemat.cpp
  linalg/vector.cpp
  makefile
Labels: hpc, minor, usage

#839 [okina] INSTALL file option updates [okina-install]
  INSTALL
  config/defaults.mk
Labels: GPU, building, documentation

#840 [okina] Some tweaks and fixes in the build system [okina-build-tweaks]
  INSTALL
  config/config.mk.in
  config/defaults.mk
  fem/bilininteg_ext.cpp
  general/CMakeLists.txt
  general/cuda.hpp
  general/device.cpp
  general/occa.cpp
  general/okina.hpp
  makefile
Labels: GPU, building

#845 Some tweaks to the mfem::Device class [okina-device-tweaks]
  config/config.hpp
  examples/ex1.cpp
  examples/ex1p.cpp
  examples/ex6.cpp
  examples/ex6p.cpp
  fem/bilinearform.cpp
  fem/bilinearform_ext.cpp
  fem/bilinearform_ext.hpp
  fem/bilininteg.hpp
  fem/bilininteg_ext.cpp
  fem/bilininteg_ext.hpp
  general/cuda.cpp
  general/cuda.hpp
  general/device.cpp
  general/device.hpp
  general/mem_manager.cpp
  general/mem_manager.hpp
  general/occa.cpp
  general/occa.hpp
  general/okina.hpp
  linalg/densemat.cpp
  linalg/dtensor.hpp
  linalg/sparsemat.cpp
  linalg/vector.cpp
Labels: GPU, general

#848 Okina rename [okina-rename]
  CHANGELOG
  fem/bilinearform_ext.cpp
  fem/bilininteg_ext.cpp
  general/CMakeLists.txt
  general/array.cpp
  general/device.cpp
  general/forall.hpp
  general/mem_manager.cpp
  general/mem_manager.hpp
  general/occa.cpp
  general/table.cpp
  linalg/densemat.cpp
  linalg/operator.cpp
  linalg/sparsemat.cpp
  linalg/vector.cpp
Labels: GPU

#850 Okina fallback kernels [okina-fallback-kernels]
  fem/bilininteg_ext.cpp
Labels: GPU, enhancement, fem

#849 Okina mm object [okina-mm-object]
  fem/bilinearform.cpp
  fem/bilininteg_ext.cpp
  fem/fespace.cpp
  fem/pfespace.cpp
  general/array.cpp
  general/array.hpp
  general/mem_manager.cpp
  general/mem_manager.hpp
  general/occa.cpp
  general/table.cpp
  linalg/blockmatrix.cpp
  linalg/densemat.cpp
  linalg/densemat.hpp
  linalg/dtensor.hpp
  linalg/hypre.cpp
  linalg/sparsemat.cpp
  linalg/vector.cpp
  linalg/vector.hpp
  mesh/ncmesh.cpp
  mesh/pmesh.cpp
Labels: GPU, bug, general

#852 Lambda const propagation [lambda-capture-problem]
  fem/bilininteg_ext.cpp
Labels: GPU, bug, general

#851 Updates in the examples, class BilinearForm and related [okina-bilinearform-updates]
  examples/ex1.cpp
  examples/ex1p.cpp
  examples/ex6.cpp
  examples/ex6p.cpp
  fem/bilinearform.cpp
  fem/bilinearform.hpp
  fem/bilinearform_ext.cpp
  fem/bilinearform_ext.hpp
  fem/bilininteg_ext.cpp
  fem/gridfunc.hpp
  fem/pbilinearform.cpp
  fem/pbilinearform.hpp
  linalg/handle.hpp
  mesh/pmesh.cpp
Labels: GPU, examples & miniapps

#859 Fix error messages when installing *.okl files [install-okl-fix]
  makefile
Labels: building, in-next, minor

#837 Update hypre version and point users to the LLNL repository for hypre [rcarson3:hypre-dep-dev]
  .travis.yml
  INSTALL
  config/defaults.cmake
  config/defaults.mk
Labels: building, in-next, linalg

#863 Fix a bug in the CMake file for the unit tests [cmake-unit-tests-fix]
  tests/unit/CMakeLists.txt
Labels: bug, building, in-next, testing

#871 Bugfix/windows
  .appveyor.yml
  CMakeLists.txt
  tests/unit/fem/test_datacollection.cpp
  tests/unit/fem/test_inversetransform.cpp
Labels: Windows, building, in-next

#868 Remove CU driver calls [okina-nodrv]
  config/config.hpp
  config/defaults.mk
  general/cuda.cpp
  general/cuda.hpp
  general/device.cpp
  general/device.hpp
  general/forall.hpp
  general/mem_manager.cpp
  general/occa.hpp
  linalg/vector.cpp
  makefile
Labels: GPU, WIP, building, enhancement, general, in-next

#862 Okina-CMake: CUDA, OCCA, RAJA + MPI [okina-cmake]
  CMakeLists.txt
  INSTALL
  config/XSDKDefaults.cmake
  config/cmake/MFEMConfig.cmake.in
  config/cmake/config.hpp.in
  config/cmake/modules/FindOCCA.cmake
  config/cmake/modules/FindRAJA.cmake
  config/cmake/modules/MfemCmakeUtilities.cmake
  config/defaults.cmake
  general/forall.hpp
  makefile
Labels: WIP, building, enhancement, in-next

#882 Update device sample runs [autotest-devices]
  config/sample-runs.sh
  examples/ex1.cpp
  examples/ex1p.cpp
  examples/ex6.cpp
  examples/ex6p.cpp
Labels: in-next, testing

#875 Okina ex6fix [okina-ex6fix]
  CHANGELOG
  CMakeLists.txt
  fem/bilinearform.cpp
  general/cuda.hpp
  linalg/sparsemat.cpp
  linalg/sparsemat.hpp
  mesh/pmesh.cpp
Labels: GPU, bug, enhancement, in-next, linalg

#870 Updated documentation to mention GPU support [4.0-rc2-docs]
  CHANGELOG
  CONTRIBUTING.md
  INSTALL
  README
  doc/CodeDocumentation.dox
Labels: GPU, documentation, in-next

#884 Add IMEX functionality to advection-diffusion example (ex23)
  examples/ex23p.cpp
Labels: enhancement, examples & miniapps
