Repository mfem/mfem, pull requests merged in 2019-02, with the labels that each got.

#681 Fixed BlockVector Update method [najlkin:pr5]
  linalg/blockvector.cpp
  linalg/blockvector.hpp
Labels: in-next, linalg, minor

#747 Okina Makefile fix [artv3/okina-makefile-fix]
  makefile
Labels: GPU, building

#727 Okina - RAJA (seq, omp, cuda) backend [artv3/okina-raja]
  config/config.hpp.in
  config/config.mk.in
  config/defaults.mk
  examples/ex1.cpp
  general/CMakeLists.txt
  general/config.cpp
  general/config.hpp
  general/cuda.cpp
  general/okina.hpp
  general/raja.hpp
  makefile
Labels: GPU, enhancement

#724 Update strumpack interface for version 3
  CHANGELOG
  INSTALL
  config/defaults.cmake
  config/defaults.mk
  examples/CMakeLists.txt
  examples/ex11p.cpp
  examples/makefile
  linalg/strumpack.cpp
  linalg/strumpack.hpp
  miniapps/nurbs/ex11p.cpp
Labels: building, in-next, minor

#744 Fix face-neighbor-data for nonconforming AMR meshes
  CHANGELOG
  mesh/pmesh.cpp
Labels: amr, bug, in-next, mesh

#728 Stefanozampini/fix int64build
  linalg/handle.cpp
  linalg/hypre.cpp
  linalg/petsc.cpp
  mesh/mesh.cpp
  mesh/nurbs.cpp
Labels: bug, building, enhancement, in-next
