Repository mfem/mfem, pull requests merged in 2019-01, with the labels that each got.

#721 Okina no-leaks [okina-leaks]
  examples/ex1.cpp
  fem/bilininteg.cpp
  fem/bilininteg.hpp
  fem/coefficient.cpp
  fem/doftoquad.cpp
  fem/doftoquad.hpp
  fem/kBilinIntegDiffusion.cpp
  fem/kBilinIntegDiffusion.hpp
  fem/kernels/kGeometry.cpp
  fem/kernels/kGeometry.hpp
  general/karray.hpp
  general/mm.cpp
  general/mm.hpp
  mesh/mesh.cpp
  mesh/mesh.hpp
Labels: enhancement, general

#723 Namespace okina kernels [okina-kernels-dev]
  fem/CMakeLists.txt
  fem/bilinearform.hpp
  fem/bilinearform_ext.cpp
  fem/bilinearform_ext.hpp
  fem/doftoquad.cpp
  fem/doftoquad.hpp
  fem/fe.cpp
  fem/fespace_ext.cpp
  fem/fespace_ext.hpp
  fem/kBilinIntegDiffusion.cpp
  fem/kernels/CMakeLists.txt
  fem/kernels/Geometry.cpp
  fem/kernels/Geometry.hpp
  fem/kernels/Geometry2D.cpp
  fem/kernels/Geometry3D.cpp
  fem/kernels/GlobalToLocal.cpp
  fem/kernels/GlobalToLocal.hpp
  fem/kernels/IntDiffusion.hpp
  fem/kernels/IntDiffusionAssemble.cpp
  fem/kernels/IntDiffusionMultAdd.cpp
  fem/kernels/LocalToGlobal.cpp
  fem/kernels/LocalToGlobal.hpp
  fem/kernels/kIntDiffusion.hpp
  general/CMakeLists.txt
  general/array_ext.hpp
  linalg/densemat.cpp
  linalg/kernels/densemat.cpp
  linalg/kernels/densemat.hpp
  linalg/kernels/sparsemat.cpp
  linalg/kernels/sparsemat.hpp
  linalg/kernels/vector.cpp
  linalg/kernels/vector.hpp
  linalg/operator.cpp
  linalg/sparsemat.cpp
  linalg/vector.cpp
  mesh/kernels/mesh.cpp
  mesh/kernels/mesh.hpp
  mesh/mesh.cpp
Labels: GPU, enhancement

#720 Clean memory manager [jdahm/okina-mm-dev]
  fem/bilinearform_ext.cpp
  fem/bilininteg.cpp
  fem/bilininteg.hpp
  fem/coefficient.cpp
  fem/doftoquad.cpp
  fem/doftoquad.hpp
  fem/fespace_ext.cpp
  fem/fespace_ext.hpp
  fem/kBilinIntegDiffusion.cpp
  fem/kBilinIntegDiffusion.hpp
  fem/kernels/Geometry.cpp
  fem/kernels/Geometry.hpp
  fem/kernels/GlobalToLocal.cpp
  fem/kernels/IntDiffusionAssemble.cpp
  fem/kernels/IntDiffusionMultAdd.cpp
  fem/kernels/LocalToGlobal.cpp
  general/array_ext.hpp
  general/mm.cpp
  general/mm.hpp
  general/occa.hpp
  general/okina.hpp
  linalg/kernels/densemat.cpp
  linalg/kernels/sparsemat.cpp
  linalg/kernels/vector.cpp
  mesh/kernels/mesh.cpp
  mesh/mesh.cpp
  mesh/mesh.hpp
Labels: GPU, enhancement

#635 Adding C_0 continuous periodicity to NURBS meshes [periodic-nurbs-v2-dev]
  CHANGELOG
  fem/fespace.cpp
  mesh/nurbs.cpp
  mesh/nurbs.hpp
  miniapps/nurbs/CMakeLists.txt
  miniapps/nurbs/ex1.cpp
  miniapps/nurbs/makefile
Labels: enhancement, in-next, mesh

#731 Okina memory manager segfault fix
  general/mm.cpp
  general/mm.hpp
  linalg/kernels/densemat.cpp
Labels: GPU, bug
