Repository mfem/mfem, pull requests merged in 2021-11, with the labels that each got.

#2611 Add HypreParVector::Read
  linalg/hypre.cpp
  linalg/hypre.hpp
  tests/unit/linalg/test_hypre_vector.cpp
Labels: enhancement, minor, linalg, in-next, in-review

#2607 Add Size & MemoryType Array Constructor
  general/array.hpp
Labels: minor, in-next, GPU, in-review

#2423 Additional Device Kernels
  linalg/kernels.hpp
Labels: minor, in-next, GPU, in-review

#2367 Make `Memory<T>::Delete()` reset the `Memory<T>` object.
  general/mem_manager.hpp
Labels: enhancement, in-next, in-review

#2406 cmake: install examples when enabled
  CMakeLists.txt
  config/cmake/modules/MfemCmakeUtilities.cmake
Labels: examples & miniapps, in-next, in-review, cmake

#2645 Include `omp` header on macOS [omp-macos]
  CMakeLists.txt
Labels: building, Mac, in-next, in-review, cmake

#2649 Small fix in Github actions
  .github/workflows/mfem-analysis.yml
Labels: in-next, github, testing, in-review

#2366 extend `ConduitDataCollection` to support `adjsets` exporting
  CHANGELOG
  fem/conduitdatacollection.cpp
  fem/conduitdatacollection.hpp
Labels: mesh, general, in-next, in-review

#2659 Allow for customizing compiler flags for generating dependencies
  config/defaults.mk
  makefile
Labels: building, Mac, minor, in-next, in-review

#2638 More threads/block for SmemPADiffusionApply3D
  fem/bilininteg_diffusion_pa.cpp
Labels: enhancement, in-next, GPU, in-review

#2358 Use `Reset()` in default constructor of `Memory<T>`.
  fem/staticcond.cpp
  general/mem_manager.hpp
  general/table.cpp
  general/table.hpp
  linalg/densemat.cpp
  linalg/densemat.hpp
  linalg/petsc.cpp
  linalg/sparsemat.cpp
  linalg/symmat.cpp
  linalg/vector.cpp
  linalg/vector.hpp
Labels: enhancement, in-next, GPU, in-review

#2652 Update with latest changes in hypre
  linalg/hypre.cpp
Labels: linalg, in-next, in-review

#2661 In Gitlab CI, disable the `rebaseline` job for `master`
  .gitlab/quartz-baseline.yml
Labels: minor, in-next, testing, in-review

#2639 Add move constructors/assignment for Vector and HypreParVector [hypreparvec-move-dev]
  CHANGELOG
  linalg/hypre.cpp
  linalg/hypre.hpp
  linalg/vector.cpp
  linalg/vector.hpp
  tests/unit/CMakeLists.txt
  tests/unit/linalg/test_hypre_vector.cpp
  tests/unit/linalg/test_vector.cpp
Labels: in-next, in-review

#2383 AD capabilities in mfem - autodiff
  .gitignore
  CHANGELOG
  CMakeLists.txt
  CONTRIBUTING.md
  INSTALL
  config/cmake/MFEMConfig.cmake.in
  config/cmake/config.hpp.in
  config/cmake/modules/FindCODIPACK.cmake
  config/config.hpp.in
  config/config.mk.in
  config/defaults.cmake
  config/defaults.mk
  doc/CodeDocumentation.conf.in
  doc/CodeDocumentation.dox
  makefile
  miniapps/CMakeLists.txt
  miniapps/autodiff/CMakeLists.txt
  miniapps/autodiff/admfem.hpp
  miniapps/autodiff/example.hpp
  miniapps/autodiff/fdual.hpp
  miniapps/autodiff/makefile
  miniapps/autodiff/par_example.cpp
  miniapps/autodiff/seq_example.cpp
  miniapps/autodiff/seq_test.cpp
  miniapps/autodiff/taddensemat.hpp
  miniapps/autodiff/tadvector.hpp
Labels: enhancement, general, in-next, in-review, request-for-comments

#2570 Added AddDomainIntegrator with marker for (Par)ComplexLinearForm and (Par)SesquilinearForm
  fem/complex_fem.cpp
  fem/complex_fem.hpp
Labels: enhancement, fem, in-next, in-review
