Repository mfem/mfem, pull requests merged in 2021-08, with the labels that each got.

#2441 fix GetElementSize for surface meshes
  mesh/mesh.cpp
Labels: bug, minor, mesh, in-next, in-review

#2399 Face neighbor data bugfix [bugfix-face-restriction]
  fem/prestriction.cpp
  fem/restriction.cpp
Labels: bug, fem, in-next, in-review

#2357 Verify that sizes in `Memory<T>` copy methods are compatible.
  general/mem_manager.hpp
Labels: enhancement, in-next, GPU, in-review

#2447 Fix MFEM_VERIFY in TrueAddMult
  fem/pbilinearform.cpp
Labels: bug, in-next, in-review

#1922 hr-adaptivity with TMOP-based error estimators
  CHANGELOG
  fem/CMakeLists.txt
  fem/fem.hpp
  fem/tmop.cpp
  fem/tmop.hpp
  fem/tmop_amr.cpp
  fem/tmop_amr.hpp
  fem/tmop_tools.cpp
  mesh/ncmesh.cpp
  mesh/ncmesh.hpp
  mesh/pncmesh.cpp
  mesh/pncmesh.hpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/mesh-optimizer.hpp
  miniapps/meshing/pmesh-optimizer.cpp
Labels: enhancement, mesh, in-next, in-review

#2425 Update spack package [build/bernede1/update-spack-package]
  .gitlab/lassen.yml
  tests/gitlab/build_and_test
  tests/gitlab/get_mfem_uberenv
Labels: building, in-next, testing, in-review

#2462 Minor fixes to resolve bugs introduced in TMOP
  fem/gridfunc.hpp
  fem/pgridfunc.hpp
  general/mem_manager.hpp
  linalg/vector.hpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
Labels: bug, mesh, in-next, in-review

#2445 Improve CUSPARSE SPMV alg selection
  linalg/sparsemat.cpp
Labels: linalg, in-next, GPU, in-review

#2456 Const parameter for mesh copy assignment
  mesh/mesh.hpp
Labels: bug, mesh, in-next, in-review

#2470 SLURM update workaround
  .gitlab-ci.yml
Labels: in-next, testing, in-review

#2467 Add additional caliper macros
  examples/caliper/ex1.cpp
  examples/caliper/ex1p.cpp
  general/annotation.hpp
  general/forall.hpp
Labels: minor, in-next, testing, in-review

#2468 Adjust true add mult to use MFEM's GetProlongationMatrix()
  fem/pbilinearform.cpp
  fem/pbilinearform.hpp
Labels: enhancement, in-next, GPU, in-review

#2478 Add caliper to the list of sub-directories under examples
  examples/caliper/ex1p.cpp
  makefile
Labels: examples & miniapps, in-next, in-review

#2481 Add citation links to the GitHub repo
  CITATION.cff
Labels: minor, in-next, documentation, github, in-review

#2479 Use l1-Jacobi smoother for ADS with CUDA [ads-cuda-use-jacobi]
  linalg/hypre.cpp
Labels: bug, in-next, GPU, in-review

#1046 Removing need for ReorientTetMesh [no-tet-reorder-dev]
  CHANGELOG
  examples/ex13p.cpp
  examples/ex24.cpp
  examples/ex24p.cpp
  examples/ex25.cpp
  examples/ex25p.cpp
  examples/ex3.cpp
  examples/ex3p.cpp
  examples/ex4p.cpp
  examples/ex8p.cpp
  examples/petsc/ex3p.cpp
  examples/petsc/ex4p.cpp
  fem/CMakeLists.txt
  fem/bilinearform.cpp
  fem/doftrans.cpp
  fem/doftrans.hpp
  fem/fe_coll.cpp
  fem/fem.hpp
  fem/fespace.cpp
  fem/fespace.hpp
  fem/gridfunc.cpp
  fem/linearform.cpp
  fem/pfespace.cpp
  fem/pfespace.hpp
  fem/pgridfunc.cpp
  fem/transfer.cpp
  general/stable3d.cpp
  linalg/densemat.hpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/mesh_readers.cpp
  mesh/pmesh.cpp
  mesh/pmesh.hpp
  mesh/pumi.hpp
  miniapps/electromagnetics/joule.cpp
  tests/unit/fem/test_3d_bilininteg.cpp
  tests/unit/fem/test_build_dof_to_arrays.cpp
  tests/unit/fem/test_doftrans.cpp
  tests/unit/fem/test_domain_int.cpp
  tests/unit/fem/test_eigs.cpp
  tests/unit/fem/test_get_value.cpp
  tests/unit/fem/test_lin_interp.cpp
Labels: enhancement, fem, in-next, in-review

#2482 Documenting the linearization of K(u) in ex16(p).
  examples/ex16.cpp
  examples/ex16p.cpp
Labels: in-next, documentation, in-review
