Repository mfem/mfem, pull requests merged in 2021-12, with the labels that each got.

#2668 Bug-fix: Adding appropriate doftransformations for high-order ND tet elements in RefineOperator/PRefineOperator Mult and MultTranspose
  fem/doftrans.cpp
  fem/doftrans.hpp
  fem/fespace.cpp
  fem/transfer.cpp
  tests/unit/fem/test_doftrans.cpp
  tests/unit/fem/test_transfer.cpp
Labels: bug, fem, in-next, in-review

#2631 Guard add_test calls with MFEM_ENABLE_TESTING
  examples/CMakeLists.txt
  examples/amgx/CMakeLists.txt
  examples/caliper/CMakeLists.txt
  examples/ginkgo/CMakeLists.txt
  examples/hiop/CMakeLists.txt
  examples/petsc/CMakeLists.txt
  examples/pumi/CMakeLists.txt
  examples/sundials/CMakeLists.txt
  examples/superlu/CMakeLists.txt
  miniapps/electromagnetics/CMakeLists.txt
  miniapps/meshing/CMakeLists.txt
  miniapps/nurbs/CMakeLists.txt
  miniapps/performance/CMakeLists.txt
  miniapps/solvers/CMakeLists.txt
Labels: building, in-next, in-review, cmake

#2592 Adding Piecewise coefficient classes [pw-coefs-dev]
  fem/coefficient.cpp
  fem/coefficient.hpp
  tests/unit/CMakeLists.txt
  tests/unit/fem/test_coefficient.cpp
Labels: in-next, in-review

#2655 Fix Memory leaks in PMesh
  mesh/pmesh.cpp
Labels: bug, in-next, in-review

#2698 Remove nvcc warnings about partially overridden virtual functions [nvwarnings]
  fem/coefficient.hpp
  fem/doftrans.hpp
Labels: enhancement, building, minor, in-next, GPU, low-impact, in-review

#2702 MFEM Code of Conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README
Labels: in-next, documentation, in-review, community

#2656 GridFunction coefficients that work with LOR preconditioning
  CHANGELOG
  fem/coefficient.cpp
  fem/eltrans.cpp
  fem/eltrans.hpp
  fem/tmop.cpp
  mesh/mesh.cpp
  mesh/pmesh.cpp
  tests/unit/CMakeLists.txt
  tests/unit/fem/test_lor.cpp
Labels: enhancement, fem, in-next, in-review

#2684 TMOP clean up
  fem/tmop.cpp
  fem/tmop.hpp
  fem/tmop/tmop_pa.cpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
Labels: mesh, in-next, in-review

#2677 Positive diagonal in Jacobi smoothers
  .gitlab/configs/lassen-config.yml
  linalg/solvers.cpp
  linalg/solvers.hpp
  linalg/sparsemat.cpp
  linalg/sparsemat.hpp
  linalg/sparsesmoothers.cpp
  linalg/sparsesmoothers.hpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
Labels: in-next, in-review

#2629 Add unary + to AutoSIMD
  CHANGELOG
  linalg/simd/auto.hpp
  linalg/simd/m128.hpp
  linalg/simd/m256.hpp
  linalg/simd/m512.hpp
  linalg/simd/qpx256.hpp
  linalg/simd/sve.hpp
  linalg/simd/vsx128.hpp
  miniapps/performance/ex1.cpp
  miniapps/performance/ex1p.cpp
Labels: bug, hpc, in-next, low-impact, in-review

#2519 Modernize print level semantics
  CHANGELOG
  fem/tmop_tools.cpp
  linalg/constraints.cpp
  linalg/solvers.cpp
  linalg/solvers.hpp
  linalg/sundials.cpp
  linalg/sundials.hpp
Labels: linalg, in-next, in-review

#2722 Fix `ParFiniteElementSpace::GetEssentialVDofs()` for non-conforming meshes
  fem/pfespace.cpp
Labels: bug, fem, in-next, amr, in-review

#2709 Fix some compiler warnings from new clang and gcc versions
  fem/conduitdatacollection.cpp
  fem/fmsconvert.cpp
  fem/qinterp/eval.hpp
  fem/tmop/tmop_pa_da3.cpp
  fem/tmop/tmop_pa_h3s_c0.cpp
  fem/tmop/tmop_pa_p3_c0.cpp
  fem/tmop/tmop_pa_w3_c0.cpp
  linalg/simd/auto.hpp
  linalg/simd/m128.hpp
  linalg/simd/m256.hpp
  linalg/simd/m512.hpp
  linalg/simd/qpx256.hpp
  linalg/simd/sve.hpp
  linalg/simd/vsx128.hpp
  mesh/ncmesh.hpp
Labels: building, minor, in-next, in-review

#2730 Fix size of ScaledOperator and add MultTranspose
  linalg/operator.hpp
Labels: bug, minor, in-next, low-impact, in-review
