Repository mfem/mfem, pull requests merged in 2022-10, with the labels that each got.

#3240 Fix bug for markers in `LinearFormExtension::Assemble`
  fem/linearform_ext.cpp
Labels: bug, in-next, in-review

#3243 Fix a bug and a typo
  CMakeLists.txt
  general/mem_manager.hpp
Labels: bug, building, in-next, GPU, in-review

#3136 Modify GridFunction::GetTrueVector behavior to SetTrueVector if `t_vec` does not already exist
  CHANGELOG
  fem/gridfunc.cpp
  fem/gridfunc.hpp
Labels: in-next, in-review

#3170 Support for SUNDIALS v6
  CHANGELOG
  config/defaults.mk
  examples/sundials/ex10.cpp
  examples/sundials/ex10p.cpp
  examples/sundials/ex16.cpp
  examples/sundials/ex16p.cpp
  examples/sundials/ex9.cpp
  examples/sundials/ex9p.cpp
  linalg/hypre.cpp
  linalg/hypre.hpp
  linalg/sundials.cpp
  linalg/sundials.hpp
  linalg/vector.cpp
  linalg/vector.hpp
Labels: in-next, API change, in-review

#3146 Update of the 3D tmop metrics
  .gitignore
  CHANGELOG
  fem/tmop.cpp
  fem/tmop.hpp
  linalg/densemat.cpp
  linalg/densemat.hpp
  linalg/invariants.hpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
  miniapps/tools/CMakeLists.txt
  miniapps/tools/check-tmop-metric.cpp
Labels: in-next, in-review, TMOP

#3233 Change performance miniapps compiler flags for Apple M1
  miniapps/performance/CMakeLists.txt
Labels: bug, building, Mac, in-next, low-impact, in-review

#3096 Fix memory leak found in HypreAMS when SetOperator is called multiple times [hypreams-mem-leak-fix]
  linalg/hypre.cpp
  linalg/hypre.hpp
Labels: in-next, in-review

#3179 Exploit PETSc matrix block structure
  examples/petsc/ex10p.cpp
  examples/petsc/ex2p.cpp
  examples/petsc/makefile
  examples/petsc/rc_ex2p
  examples/petsc/rc_ex2p_asm
  linalg/petsc.cpp
  linalg/petsc.hpp
Labels: linalg, in-next, in-review, PETSc

#3256 Fix parallel hang in LinearForm::SupportsDevice
  fem/linearform.cpp
Labels: bug, in-next, in-review

#3230 Kershaw transformation
  miniapps/common/mesh_extras.cpp
  miniapps/common/mesh_extras.hpp
  miniapps/meshing/CMakeLists.txt
  miniapps/meshing/mesh-explorer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
Labels: enhancement, mesh, in-next, in-review

#3043 Node ordering in GSLIBFindPoints and TMOP
  CHANGELOG
  fem/gslib.cpp
  fem/gslib.hpp
  fem/tmop.cpp
  fem/tmop.hpp
  fem/tmop/tmop_pa.cpp
  fem/tmop_tools.cpp
  fem/tmop_tools.hpp
  miniapps/gslib/field-interp.cpp
  miniapps/gslib/findpts.cpp
  miniapps/gslib/pfindpts.cpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
Labels: fem, in-next, in-review

#3235 [SQUASH] Assembly levels for LinearForm
  CHANGELOG
  fem/bilinearform.cpp
  fem/bilinearform.hpp
  fem/linearform.cpp
  fem/linearform.hpp
  fem/plinearform.cpp
  fem/plinearform.hpp
  fem/tmop_tools.cpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  miniapps/meshing/minimal-surface.cpp
  miniapps/meshing/pminimal-surface.cpp
  tests/unit/fem/test_linearform_ext.cpp
Labels: fem, hpc, in-next, high-impact, in-review

#3257 Some fixes for hypre v2.26.0
  CHANGELOG
  examples/ex5.cpp
  examples/superlu/CMakeLists.txt
  fem/ceed/solvers/algebraic.cpp
  fem/fespace.cpp
  fem/hybridization.cpp
  fem/pbilinearform.cpp
  fem/pfespace.cpp
  fem/transfer.cpp
  linalg/hypre.cpp
  linalg/hypre.hpp
  linalg/sparsemat.cpp
  linalg/sparsemat.hpp
  miniapps/common/mesh_extras.hpp
  miniapps/shifted/lsf_integral.cpp
  tests/unit/fem/test_assembly_levels.cpp
  tests/unit/fem/test_pa_coeff.cpp
  tests/unit/fem/test_pa_grad.cpp
  tests/unit/fem/test_pa_idinterp.cpp
  tests/unit/fem/test_pa_kernels.cpp
Labels: bug, in-next, GPU, in-review

#3262 check comm pkg
  linalg/hypre.cpp
Labels: bug, linalg, in-next, in-review

#3258 Fix for autotest error in Remhos
  fem/fespace.hpp
  fem/qfunction.cpp
  mesh/mesh.cpp
Labels: bug, in-next, in-review

#3199 Final changes for mfem-4.5
  CHANGELOG
  CMakeLists.txt
  INSTALL
  config/defaults.mk
  config/sample-runs.sh
  config/vcpkg/ports/metis-mfem/vcpkg.json
  doc/CodeDocumentation.conf.in
  fem/bilininteg.hpp
  fem/bilininteg_hcurl.cpp
  fem/bilininteg_hdiv.cpp
  fem/coefficient.hpp
  fem/estimators.cpp
  fem/fe/fe_nd.cpp
  fem/fe/fe_rt.cpp
  fem/gridfunc.cpp
  fem/linearform.cpp
  fem/moonolith/mortarintegrator.hpp
  fem/tmop.hpp
  general/mem_manager.cpp
  general/mem_manager.hpp
  general/zstr.hpp
  linalg/complex_densemat.cpp
  linalg/densemat.hpp
  linalg/hypre.cpp
  linalg/hypre.hpp
  linalg/superlu.cpp
  linalg/tensor.hpp
  makefile
  mesh/mesh.cpp
  mesh/submesh/ptransfermap.hpp
  miniapps/toys/life.cpp
Labels: in-next, releases, in-review

#3266 Update version numbers to 4.5.1 -- a new development version
  CHANGELOG
  CMakeLists.txt
  doc/CodeDocumentation.conf.in
  makefile
Labels: in-next, in-review

#3270 Fix bug in mondrian miniapp
  miniapps/toys/mondrian.cpp
Labels: bug, minor, in-next, in-review
