Repository mfem/mfem, pull requests merged in 2022-06, with the labels that each got.

#3060 Solves cmake include directory ordering issue
  CMakeLists.txt
Labels: bug, building, in-next, in-review, cmake

#3062 Fix no convergence output in Newton solver
  linalg/solvers.cpp
Labels: bug, minor, in-next, in-review

#3047 Add HasSpMatElim
  fem/bilinearform.hpp
Labels: in-next, in-review

#3054 Add additional orders to conv + trace
  fem/bilininteg_convection_pa.cpp
  fem/bilininteg_dgtrace_pa.cpp
Labels: minor, hpc, in-next, in-review

#3041 Shared Memory FaceQuadratureInterpolator::Eval3D
  fem/quadinterpolator_face.cpp
  fem/quadinterpolator_face.hpp
Labels: in-next, GPU, in-review

#3064 Explicitly delete some Vector operator overloads
  linalg/vector.hpp
Labels: minor, linalg, in-next, in-review

#3044 Extend `ex33` to arbitrary fractional exponents
  examples/ex33.cpp
  examples/ex33.hpp
  examples/ex33p.cpp
Labels: enhancement, examples & miniapps, in-next, in-review

#3024 Quieter unit tests
  tests/unit/README.md
  tests/unit/cunit_test_main.cpp
  tests/unit/fem/test_assemblediagonalpa.cpp
  tests/unit/fem/test_blocknonlinearform.cpp
  tests/unit/fem/test_calccurlshape.cpp
  tests/unit/fem/test_calcdivshape.cpp
  tests/unit/fem/test_calcdshape.cpp
  tests/unit/fem/test_calcshape.cpp
  tests/unit/fem/test_calcvshape.cpp
  tests/unit/fem/test_datacollection.cpp
  tests/unit/fem/test_eigs.cpp
  tests/unit/fem/test_face_elem_trans.cpp
  tests/unit/fem/test_face_permutation.cpp
  tests/unit/fem/test_get_value.cpp
  tests/unit/fem/test_inversetransform.cpp
  tests/unit/fem/test_operatorjacobismoother.cpp
  tests/unit/fem/test_pa_coeff.cpp
  tests/unit/fem/test_project_bdr.cpp
  tests/unit/fem/test_quadf_coef.cpp
  tests/unit/fem/test_quadinterpolator.cpp
  tests/unit/fem/test_quadraturefunc.cpp
  tests/unit/linalg/test_chebyshev.cpp
  tests/unit/linalg/test_constrainedsolver.cpp
  tests/unit/linalg/test_hypre_ilu.cpp
  tests/unit/linalg/test_matrix_block.cpp
  tests/unit/linalg/test_matrix_hypre.cpp
  tests/unit/linalg/test_matrix_rectangular.cpp
  tests/unit/linalg/test_matrix_sparse.cpp
  tests/unit/linalg/test_matrix_square.cpp
  tests/unit/linalg/test_ode.cpp
  tests/unit/linalg/test_ode2.cpp
  tests/unit/mesh/test_ncmesh.cpp
  tests/unit/pcunit_test_main.cpp
  tests/unit/punit_test_main.cpp
  tests/unit/run_unit_tests.hpp
  tests/unit/unit_test_main.cpp
  tests/unit/unit_tests.hpp
Labels: in-next, testing, in-review

#2934 Add umpire pools to face geometric factor memory
  fem/bilininteg_dgtrace_pa.cpp
  mesh/mesh.cpp
  mesh/mesh.hpp
Labels: in-next, in-review

#3078 Disable Build Deploy Container workflow in forks
  .github/workflows/build-container.yaml
Labels: minor, in-next, github, in-review
