Repository mfem/mfem, pull requests merged in 2023-02, with the labels that each got.

#3357 Documentation improvements for `GetTransformation()`
  mesh/mesh.hpp
  mesh/pmesh.hpp
Labels: in-next, documentation, in-review

#3445 Update version of mpi4py/setup-mpi action
  .github/workflows/builds-and-tests.yml
Labels: in-next, testing, in-review

#3405 Initial and relative final norm for IterativeSolvers.
  linalg/constraints.cpp
  linalg/solvers.cpp
  linalg/solvers.hpp
Labels: enhancement, linalg, in-next, in-review

#3364 Fix double-free of HypreParVector after move with hypre+GPU
  general/mem_manager.hpp
  linalg/hypre.cpp
  linalg/vector.cpp
Labels: in-next, GPU, in-review

#3441 Add missing `inline`
  general/backends.hpp
Labels: in-next, in-review

#3430 Improve Doxygen comments for Mesh::GetNodes and related functions
  mesh/mesh.hpp
Labels: in-next, documentation, in-review

#2980 Add support for pyramid elements in Gmsh meshes
  CHANGELOG
  mesh/mesh_readers.cpp
  mesh/pmesh.cpp
Labels: mesh, in-next, in-review

#3411 Retry git push in autotest GitLab CI
  .gitlab/quartz-baseline.yml
  .gitlab/scripts/git_try_to_push
  .gitlab/scripts/report_build_and_test_failure
  .gitlab/scripts/report_build_and_test_success
Labels: in-next, testing, in-review

#3440 Support LOR transfer with smaller LOR spaces
  fem/transfer.cpp
  fem/transfer.hpp
  miniapps/tools/lor-transfer.cpp
Labels: bug, in-next, in-review

#3412 TMOP - balancing of compound metrics
  .gitignore
  CHANGELOG
  fem/tmop.cpp
  fem/tmop.hpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
  miniapps/tools/makefile
  miniapps/tools/tmop-metric-magnitude.cpp
Labels: in-next, in-review, TMOP

#3458 Change intersect algorithm to not use goto
  mesh/ncmesh.cpp
Labels: in-next, in-review

#3275 Add default constructor to ParFiniteElementSpaceHierarchy [add_default_constructor]
  fem/fespacehierarchy.hpp
Labels: minor, fem, in-next, in-review

#3452 Avoid global initialization issues in (p)minimal-surface
  miniapps/meshing/minimal-surface.cpp
  miniapps/meshing/pminimal-surface.cpp
Labels: bug, examples & miniapps, in-next, in-review

#3363 Mesh reflector miniapp
  .gitignore
  CHANGELOG
  fem/gridfunc.hpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  miniapps/meshing/CMakeLists.txt
  miniapps/meshing/makefile
  miniapps/meshing/reflector.cpp
Labels: mesh, in-next, in-review

#3468 Bug fixes in GSLib and TMOP
  fem/gslib.cpp
  fem/tmop.cpp
Labels: bug, in-next, in-review

#3462 Cmake global flag fix
  CMakeLists.txt
Labels: bug, building, in-next, in-review

#3474 Use GeometricFactors::DETERMINANTS in PA mass integrator
  fem/bilininteg_mass_pa.cpp
Labels: minor, in-next, in-review

#3503 Fix an issue in `FiniteElementCollection::FiniteElementForDim`
  fem/fe_coll.cpp
  fem/fe_coll.hpp
Labels: bug, fem, in-next, in-review

#3253 GetGradient methods for face-neighbor elements.
  CHANGELOG
  fem/gridfunc.cpp
  fem/gridfunc.hpp
  tests/unit/CMakeLists.txt
  tests/unit/fem/test_getderivative.cpp
  tests/unit/fem/test_getgradient.cpp
Labels: fem, in-next, in-review

#3314 Non-tensor H(curl) and H(div) FiniteElement::GetDofToQuad
  fem/fe/fe_base.cpp
  fem/fe/fe_base.hpp
  fem/fe/fe_nd.cpp
  fem/fe/fe_pos.hpp
  fem/fe/fe_rt.cpp
  tests/unit/CMakeLists.txt
Labels: fem, in-next, in-review
