Repository mfem/mfem, pull requests merged in 2023-01, with the labels that each got.

#3293 RAJA launch API updates
  CHANGELOG
  CMakeLists.txt
  INSTALL
  config/cmake/modules/FindRAJA.cmake
  config/cmake/modules/FindUMPIRE.cmake
  config/defaults.cmake
  config/defaults.mk
  general/forall.hpp
  miniapps/hooke/CMakeLists.txt
Labels: minor, in-next, GPU, in-review

#3362 Adds a QuadratureFunction constructor from external data
  fem/qfunction.hpp
Labels: in-next, in-review

#3389 Fix some shadow warnings
  fem/fe/fe_nd.cpp
  fem/fe/fe_rt.cpp
  general/socketstream.cpp
Labels: bug, minor, in-next, in-review

#3320 Bug fix for non-conforming meshes.
  CHANGELOG
  fem/bilinearform_ext.cpp
  fem/bilininteg_dgtrace_pa.cpp
  fem/bilininteg_transpose_ea.cpp
  fem/fespace.cpp
  fem/pfespace.cpp
  fem/quadinterpolator_face.cpp
  fem/restriction.cpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/pmesh.cpp
Labels: bug, in-next, amr, in-review

#3387 Bugfix for surface submesh boundary elements from volume
  mesh/submesh/psubmesh.cpp
  tests/unit/mesh/test_psubmesh.cpp
Labels: bug, mesh, in-next, in-review

#3075 `Multigrid::Mult` with multiple RHS
  fem/bilinearform_ext.hpp
  fem/ceed/interface/operator.cpp
  fem/ceed/interface/operator.hpp
  fem/fespace.cpp
  fem/multigrid.cpp
  fem/multigrid.hpp
  fem/prestriction.cpp
  fem/prestriction.hpp
  fem/restriction.cpp
  fem/restriction.hpp
  fem/tbilinearform.hpp
  linalg/complex_operator.hpp
  linalg/densemat.cpp
  linalg/densemat.hpp
  linalg/hypre.hpp
  linalg/operator.cpp
  linalg/operator.hpp
  linalg/petsc.hpp
  linalg/solvers.hpp
  linalg/sparsemat.hpp
Labels: in-next, in-review

#3402 Add Array move constructor, make [Par]TransferMap movable
  general/array.hpp
  mesh/submesh/ptransfermap.cpp
  mesh/submesh/ptransfermap.hpp
  mesh/submesh/submesh_utils.hpp
  mesh/submesh/transfermap.cpp
  mesh/submesh/transfermap.hpp
Labels: bug, enhancement, in-next, in-review

#3394 Remove unneeded `using` statements in coefficient.hpp
  fem/coefficient.hpp
Labels: bug, in-next, in-review

#3271 Fix DLL install directory in mingw
  CMakeLists.txt
Labels: building, Windows, in-next, in-review

#3403 Algoim configuration fix
  config/cmake/modules/FindAlgoim.cmake
  config/defaults.cmake
  miniapps/shifted/integ_algoim.cpp
  miniapps/shifted/integ_algoim.hpp
  miniapps/shifted/lsf_integral.cpp
Labels: bug, in-next, in-review

#3007 Use local L2 projection for coarsening L2 spaces on non-conforming AMR meshes [bugfix/rwa/coarsen-L2-proj]
  CHANGELOG
  fem/fe/fe_base.cpp
  fem/fe/fe_base.hpp
  fem/fe/fe_l2.hpp
  fem/fe/fe_pos.cpp
  fem/fe/fe_pos.hpp
  fem/fespace.cpp
  fem/pfespace.cpp
  mesh/mesh.cpp
  mesh/ncmesh.cpp
  tests/unit/fem/test_derefine.cpp
Labels: enhancement, in-next, amr, in-review

#3285 Fix metric 301.
  CHANGELOG
  fem/tmop.cpp
  miniapps/tools/check-tmop-metric.cpp
  miniapps/tools/makefile
Labels: bug, in-next, in-review, TMOP

#3417 Bugfix in `ParBilinearForm::TrueAddMult`
  fem/pbilinearform.cpp
  fem/pbilinearform.hpp
Labels: bug, fem, in-next, in-review
