Repository mfem/mfem, pull requests merged in 2023-08, with the labels that each got.

#3804 Add Minimum Size Check to DiscreteAdaptTC::ComputeAllElementTargets Kernel [tmop-pa-3d-min-size-check-dev]
  fem/tmop/tmop_pa_da3.cpp
Labels: in-next, in-review

#3787 Fix warning from assigned and unused variables
  tests/unit/linalg/test_operator.cpp
Labels: bug, minor, in-next, in-review

#3769 fix config/docker image instructions and dockerfiles
  config/docker/Dockerfile
  config/docker/Dockerfile.base
  config/docker/README.md
Labels: building, hpc, in-next, in-review

#3810 Support std::string in OptionsParser
  examples/ex0.cpp
  examples/ex0p.cpp
  general/optparser.cpp
  general/optparser.hpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/pmesh.cpp
  mesh/pmesh.hpp
Labels: minor, in-next, in-review

#3817 Generalize Mesh::GetFaceToBdrElMap
  mesh/mesh.cpp
Labels: minor, mesh, in-next, in-review

#3798 SVD modified to solve linear systems
  linalg/densemat.cpp
  linalg/densemat.hpp
Labels: linalg, in-next, in-review

#3659 fix make file of nurbs-interp-dev [nurbs-interp-fix-make]
  .gitignore
  CHANGELOG
  miniapps/nurbs/CMakeLists.txt
  miniapps/nurbs/makefile
  miniapps/nurbs/nurbs_curveint.cpp
Labels: bug, examples & miniapps, in-next, in-review

#3676 Fix heap overflow from variable length arrays
  fem/fe_coll.cpp
  fem/pfespace.cpp
Labels: bug, minor, in-next, in-review

#3709 Bug fixes for NC prism meshes
  fem/pfespace.cpp
  mesh/ncmesh.cpp
  mesh/pncmesh.cpp
  mesh/pncmesh.hpp
  tests/unit/mesh/test_ncmesh.cpp
Labels: bug, in-next, in-review

#3829 Update `(Par)TransferMap` to support data on GPU by copying it to CPU
  mesh/submesh/ptransfermap.cpp
  mesh/submesh/transfermap.cpp
Labels: bug, mesh, GPU, in-review

#3789 Fix shadow variable warning
  fem/gslib.cpp
Labels: bug, minor, in-next, in-review

#3822 QuadratureFunction::SaveVTU fixes
  fem/datacollection.cpp
  fem/qfunction.cpp
  fem/qfunction.hpp
Labels: minor, in-next, visualization, in-review

#3404 Nurbs auto knot2edge and free patch orientation dev [nurbs-auto-knot2edge-dev]
  CHANGELOG
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/nurbs.cpp
  mesh/nurbs.hpp
  miniapps/nurbs/CMakeLists.txt
  miniapps/nurbs/makefile
  miniapps/nurbs/meshes/two-cubes-nurbs-autoedge.mesh
  miniapps/nurbs/meshes/two-cubes-nurbs-rot.mesh
  miniapps/nurbs/meshes/two-cubes-nurbs.mesh
  miniapps/nurbs/meshes/two-cubes.ref
  miniapps/nurbs/meshes/two-squares-nurbs-autoedge.mesh
  miniapps/nurbs/meshes/two-squares-nurbs-rot.mesh
  miniapps/nurbs/meshes/two-squares-nurbs.mesh
  miniapps/nurbs/meshes/two-squares.ref
  miniapps/nurbs/nurbs_ex1.cpp
Labels: mesh, in-next, in-review

#3088 NURBS patch quadrature
  .gitignore
  CHANGELOG
  fem/CMakeLists.txt
  fem/bilinearform.cpp
  fem/bilinearform_ext.cpp
  fem/bilininteg.cpp
  fem/bilininteg.hpp
  fem/fe/fe_nurbs.hpp
  fem/fespace.cpp
  fem/fespace.hpp
  fem/integ/bilininteg_diffusion_pa.cpp
  fem/integ/bilininteg_diffusion_patch.cpp
  fem/intrules.cpp
  fem/intrules.hpp
  fem/nonlininteg.hpp
  general/array.hpp
  linalg/solvers.cpp
  linalg/solvers.hpp
  mesh/nurbs.cpp
  mesh/nurbs.hpp
  miniapps/nurbs/CMakeLists.txt
  miniapps/nurbs/makefile
  miniapps/nurbs/nurbs_patch_ex1.cpp
  tests/scripts/branch-history
  tests/unit/linalg/test_matrix_dense.cpp
Labels: fem, linalg, examples & miniapps, in-next, in-review

#3833 In GitHub actions, enable testing of debug builds under Ubuntu
  .github/workflows/builds-and-tests.yml
  fem/tmop_tools.cpp
  linalg/hypre.cpp
  linalg/solvers.cpp
  linalg/sparsemat.cpp
  miniapps/dpg/acoustics.cpp
  miniapps/dpg/convection-diffusion.cpp
  miniapps/dpg/maxwell.cpp
  miniapps/dpg/pconvection-diffusion.cpp
  miniapps/dpg/pmaxwell.cpp
  miniapps/electromagnetics/joule.cpp
  miniapps/meshing/mesh-optimizer.hpp
  miniapps/meshing/polar-nc.cpp
Labels: in-next, testing, in-review
