Repository mfem/mfem, pull requests merged in 2024-01, with the labels that each got.

#3957 Workaround for an issue in certain HIP builds
  general/error.hpp
Labels: building, in-next, GPU, in-review

#4027 Boundary LF Integrators fast assembly bug fix
  fem/integ/lininteg_boundary.cpp
Labels: bug, minor, in-next, GPU, in-review

#3746 Add internal boundary element support for NCMesh
  CHANGELOG
  fem/bilinearform.cpp
  fem/fespace.cpp
  fem/fespace.hpp
  fem/gridfunc.cpp
  fem/gridfunc.hpp
  fem/pfespace.cpp
  fem/pfespace.hpp
  fem/pgridfunc.cpp
  fem/pgridfunc.hpp
  general/communication.hpp
  general/hash.hpp
  mesh/element.hpp
  mesh/hexahedron.cpp
  mesh/hexahedron.hpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/ncmesh.cpp
  mesh/ncmesh.hpp
  mesh/pmesh.cpp
  mesh/pncmesh.cpp
  mesh/pncmesh.hpp
  mesh/point.cpp
  mesh/point.hpp
  mesh/pyramid.cpp
  mesh/pyramid.hpp
  mesh/quadrilateral.cpp
  mesh/quadrilateral.hpp
  mesh/segment.cpp
  mesh/segment.hpp
  mesh/tetrahedron.cpp
  mesh/tetrahedron.hpp
  mesh/triangle.cpp
  mesh/triangle.hpp
  mesh/wedge.cpp
  mesh/wedge.hpp
  tests/unit/CMakeLists.txt
  tests/unit/mesh/mesh_test_utils.cpp
  tests/unit/mesh/mesh_test_utils.hpp
  tests/unit/mesh/test_ncmesh.cpp
Labels: bug, enhancement, in-next, amr, in-review

#4019 Const correctness fixes for `Mesh` and `ParMesh`
  fem/coefficient.cpp
  fem/eltrans.hpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/ncmesh.cpp
  mesh/ncmesh.hpp
  mesh/pmesh.cpp
  mesh/pmesh.hpp
Labels: enhancement, mesh, in-next, in-review

#3994 PA for `GradientIntegrator` transpose
  fem/bilininteg.cpp
  fem/bilininteg.hpp
  fem/fe/fe_base.hpp
  fem/integ/bilininteg_gradient_pa.cpp
  fem/lininteg.cpp
  tests/unit/fem/test_pa_kernels.cpp
  tests/unit/linalg/test_matrix_rectangular.cpp
Labels: enhancement, in-next, GPU, in-review

#4063 Array documentation improvement
  general/array.hpp
Labels: in-next, documentation, in-review

#4069 Fix [[noreturn]] for MFEM_ABORT with Intel compilers
  general/error.hpp
  tests/unit/CMakeLists.txt
  tests/unit/general/test_error.cpp
Labels: bug, building, minor, in-next, in-review

#4055 Fix for ParNCMesh::Update()
  mesh/pncmesh.cpp
Labels: bug, minor, in-next, amr, in-review

#3806 Miniapp for block preconditioned elasticity with partial and full assembly on GPUs [full-assembly-elast-dev]
  .gitignore
  CHANGELOG
  doc/CodeDocumentation.dox
  fem/CMakeLists.txt
  fem/bilinearform_ext.cpp
  fem/bilininteg.cpp
  fem/bilininteg.hpp
  fem/fe/fe_base.cpp
  fem/fe/fe_base.hpp
  fem/fespace.cpp
  fem/fespace.hpp
  fem/integ/bilininteg_diffusion_patch.cpp
  fem/integ/bilininteg_elasticity_ea.cpp
  fem/integ/bilininteg_elasticity_kernels.cpp
  fem/integ/bilininteg_elasticity_kernels.hpp
  fem/integ/bilininteg_elasticity_pa.cpp
  fem/pfespace.cpp
  fem/pfespace.hpp
  fem/restriction.cpp
  miniapps/solvers/CMakeLists.txt
  miniapps/solvers/README
  miniapps/solvers/block_fespace_operator.cpp
  miniapps/solvers/block_fespace_operator.hpp
  miniapps/solvers/lor_elast.cpp
  miniapps/solvers/makefile
Labels: examples & miniapps, in-next, GPU, in-review

#4081 Bugfix for lor elasticity miniapp kernel
  fem/integ/bilininteg_elasticity_kernels.hpp
Labels: bug, in-next, in-review

#4087 Increase time for testing on Quartz from 45 to 60 minutes
  .gitlab/quartz-build-and-test.yml
Labels: minor, in-next, testing, in-review

#3972 Doxygen improvements to bilinearform
  fem/bilinearform.hpp
  fem/lininteg.hpp
Labels: in-next, documentation, in-review

#4090 Bump GitHub actions versions
  .github/workflows/build-container.yml
  .github/workflows/builds-and-tests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/mfem-analysis.yml
  .github/workflows/mfem-sanitizer.yml
  .github/workflows/repo-check.yml
Labels: minor, in-next, in-review, CI
