Repository mfem/mfem, pull requests merged in 2025-08, with the labels that each got.

#4923 Check for CUDA or HIP compilers
  config/config.hpp
  fem/bilininteg.hpp
  fem/dfem/util.hpp
  general/backends.hpp
  general/cuda.hpp
  general/error.hpp
  general/forall.hpp
  general/hip.hpp
  general/reducers.hpp
Labels: building, in-next, GPU, in-review

#4622 HYPRE and GPU related tweaks
  general/cuda.cpp
  general/hip.cpp
  general/mem_manager.hpp
Labels: in-next, GPU, in-review

#4725 Bilinear Operator Assembly optimizations
  INSTALL
  fem/bilinearform_ext.cpp
  fem/bilinearform_ext.hpp
  fem/integ/bilininteg_mass_pa.cpp
  fem/linearform_ext.cpp
  fem/linearform_ext.hpp
  fem/qfunction.hpp
  fem/qspace.cpp
  fem/qspace.hpp
  general/forall.hpp
  linalg/vector.cpp
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/pmesh.cpp
  mesh/pmesh.hpp
Labels: in-next, GPU, in-review

#4989 Update Xcode version in macos CI from 15.3 -> 16.4
  .github/workflows/builds-and-tests.yml
Labels: Mac, in-next, in-review, high-priority, CI

#4997 Enzyme/LLVM fixes in GitHub CI
  .github/workflows/builds-and-tests.yml
Labels: in-next, in-review, CI
