Repository mfem/mfem, pull requests merged in 2025-04, with the labels that each got.

#4701 GPU Batch Inverse Element Transform
  CHANGELOG
  fem/CMakeLists.txt
  fem/batchitrans.cpp
  fem/eltrans.cpp
  fem/eltrans.hpp
  fem/eltrans/eltrans_basis.hpp
  fem/fe/fe_base.cpp
  fem/fe/fe_base.hpp
  fem/geom.cpp
  fem/geom.hpp
  fem/gslib.cpp
  fem/gslib.hpp
  fem/gslib/findpts_local_2.cpp
  fem/gslib/findpts_local_3.cpp
  general/hash.cpp
  general/hash.hpp
  makefile
  tests/unit/data/spiral_3D_p9.mesh
  tests/unit/fem/test_inversetransform.cpp
Labels: enhancement, in-next, GPU, in-review

#4766 Remove many of the raw pointers from the new MMA solver
  linalg/mma.cpp
  linalg/mma.hpp
Labels: linalg, in-next, in-review

#4774 Tweaks for CMake 4 and GitHub CI
  CHANGELOG
  CMakeLists.txt
  INSTALL
  config/cmake/modules/FindHYPRE.cmake
  config/cmake/modules/FindMAGMA.cmake
  config/cmake/modules/MfemCmakeUtilities.cmake
  config/vcpkg/ports/metis-mfem/cmake4.patch
  config/vcpkg/ports/metis-mfem/portfile.cmake
  general/reducers.hpp
  tests/unit/fem/test_fe_compatibility.cpp
Labels: building, in-next, in-review, cmake, CI

#4750 Avoid uninitialized memory use
  fem/transfer.cpp
  miniapps/tools/lor-transfer.cpp
Labels: fem, in-next, in-review

#4780 Fix compilation errors for pyramid elements with MFEM_THREAD_SAFE
  fem/fe/fe_h1.cpp
  fem/fe/fe_l2.cpp
Labels: bug, in-review

#4783 Use Open MPI instead of MPICH in GitHub Actions
  .github/workflows/builds-and-tests.yml
Labels: bug, in-next, in-review, CI

#4798 Update version numbers to 4.8.1 -- a new development version
  CHANGELOG
  CMakeLists.txt
  doc/CodeDocumentation.conf.in
  makefile
Labels: in-next, releases, in-review

#4808 Use Open MPI instead of MPICH in Build Analysis action
  .github/workflows/mfem-analysis.yml
  linalg/hypre.hpp
Labels: in-next, in-review, CI

#4802 Suppress two warnings from newer Clang versions when using `-Wextra`
  fem/coefficient.hpp
Labels: building, minor, in-next, in-review

#4799 Fixed iterative solvers for solution-based controllers
  linalg/solvers.cpp
  linalg/solvers.hpp
Labels: bug, linalg, in-next, in-review

#4797 VTKHDF format writer
  CMakeLists.txt
  INSTALL
  config/cmake/MFEMConfig.cmake.in
  config/cmake/config.hpp.in
  config/cmake/modules/MfemCmakeUtilities.cmake
  config/config.hpp.in
  config/config.mk.in
  config/defaults.cmake
  config/defaults.mk
  fem/datacollection.cpp
  fem/datacollection.hpp
  fem/gridfunc.cpp
  fem/gridfunc.hpp
  fem/qfunction.cpp
  general/communication.cpp
  general/communication.hpp
  general/version.cpp
  makefile
  mesh/CMakeLists.txt
  mesh/mesh.cpp
  mesh/mesh.hpp
  mesh/pmesh.cpp
  mesh/vtk.cpp
  mesh/vtkhdf.cpp
  mesh/vtkhdf.hpp
  tests/unit/fem/test_datacollection.cpp
Labels: enhancement, in-next, visualization, in-review

#4816 TMOP - optional IntRule in ComputeBalancedWeights.
  fem/tmop.cpp
  fem/tmop.hpp
  miniapps/meshing/mesh-optimizer.cpp
  miniapps/meshing/pmesh-optimizer.cpp
Labels: in-next, in-review, TMOP

#4285 Moonolith h1 bugfix
  CHANGELOG
  examples/moonolith/ex1.cpp
  examples/moonolith/ex1p.cpp
  examples/moonolith/ex2p.cpp
  examples/moonolith/example_utils.hpp
  fem/moonolith/cut.cpp
  fem/moonolith/cut.hpp
  fem/moonolith/mortarassembler.cpp
  fem/moonolith/mortarassembler.hpp
  fem/moonolith/mortarintegrator.cpp
  fem/moonolith/mortarintegrator.hpp
  fem/moonolith/pmortarassembler.cpp
  fem/moonolith/transfer.cpp
  fem/moonolith/transferutils.cpp
  fem/moonolith/transferutils.hpp
Labels: mesh, fem, in-next, in-review

#4830 Use physical values in QuadratureFunction::ProjectGridFunction
  fem/qfunction.cpp
  fem/qinterp/eval_hdiv.hpp
  fem/quadinterpolator.cpp
  fem/quadinterpolator.hpp
Labels: bug, in-next, in-review

#4809 Some tweaks in class HybridizationExtension
  fem/hybridization_ext.cpp
Labels: fem, in-next, GPU, in-review
