Repository mfem/mfem, pull requests merged in 2025-07, with the labels that each got.

#4870 Improve chunking in VTKHDF writer
  fem/datacollection.cpp
  fem/datacollection.hpp
  mesh/vtkhdf.cpp
  mesh/vtkhdf.hpp
Labels: minor, in-next, visualization, in-review

#4898 Fix UB in dFEM
  fem/dfem/util.hpp
Labels: bug, in-next, in-review

#4899 [Github] Sanitizers action
  .github/actions/sanitize/config/action.yml
  .github/actions/sanitize/mfem/action.yml
  .github/actions/sanitize/mpi/action.yml
  .github/actions/sanitize/restore/action.yml
  .github/actions/sanitize/setup/action.yml
  .github/workflows/README.md
  .github/workflows/mfem-sanitizer.yml
  .github/workflows/sanitize-build-hypre.yml
  .github/workflows/sanitize-build-libcxx.yml
  .github/workflows/sanitize-build-lsan.yml
  .github/workflows/sanitize-build-metis.yml
  .github/workflows/sanitize-tests.yml
  .github/workflows/sanitizers.yml
  CHANGELOG
  fem/batchitrans.cpp
  fem/dfem/parameterspace.hpp
  fem/dfem/util.hpp
  fem/gridfunc.cpp
  fem/integ/bilininteg_mass_pa.cpp
  fem/lininteg.hpp
  fem/pfespace.cpp
  general/array.hpp
  mesh/mesh_readers.cpp
  mesh/nurbs.cpp
  mesh/nurbs.hpp
  miniapps/meshing/fit-node-position.cpp
  miniapps/solvers/block-solvers.cpp
  miniapps/solvers/block_fespace_operator.cpp
  miniapps/solvers/block_fespace_operator.hpp
  miniapps/solvers/bramble_pasciak.cpp
  miniapps/solvers/bramble_pasciak.hpp
  miniapps/solvers/darcy_solver.cpp
  miniapps/solvers/darcy_solver.hpp
  miniapps/solvers/div_free_solver.cpp
  miniapps/solvers/div_free_solver.hpp
  miniapps/spde/generate_random_field.cpp
  miniapps/toys/lissajous.cpp
  tests/unit/fem/test_assemblediagonalpa.cpp
  tests/unit/fem/test_calccurlshape.cpp
  tests/unit/fem/test_calcdivshape.cpp
  tests/unit/fem/test_fe_symmetry.cpp
  tests/unit/fem/test_operatorjacobismoother.cpp
  tests/unit/fem/test_pa_coeff.cpp
  tests/unit/fem/test_var_order.cpp
  tests/unit/general/test_reduction.cpp
  tests/unit/linalg/test_hypre_prec.cpp
  tests/unit/linalg/test_matrix_square.cpp
  tests/unit/miniapps/test_sedov.cpp
Labels: enhancement, building, in-next, in-review, CI

#4884 Fix gitignore for Windows
  .gitignore
Labels: Windows, in-next, in-review

#4954 Extend time allocation for testing on ruby from 45 to 60 minutes
  .gitlab/configs/ruby-config.yml
Labels: testing, in-review
